version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: rails s -b 0.0.0.0
    environment:
      - RAILS_ENV=development
    # volumes:
    #   - .:/usr/src/app
  builder:
    build:
      context: .
      target: builder