# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Creditworkseleniumfulltest' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'creditworkseleniumfulltest' do
    @driver.get('http://localhost:3000/accounts/sign_in')
    @driver.manage.resize_to(1200, 856)
    @driver.find_element(:id, 'account_email').send_keys('lol@gmail.com')
    @driver.find_element(:id, 'account_password').click
    @driver.find_element(:id, 'account_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.text-black:nth-child(1)').click
    @driver.find_element(:link_text, 'Редактировать профиль').click
    @driver.find_element(:link_text, 'Назад').click
    @driver.find_element(:link_text, 'Новый пост').click
    @driver.find_element(:link_text, 'Мой профиль').click
    @driver.find_element(:link_text, 'Выйти').click
    @driver.find_element(:id, 'account_email').send_keys('f@gmail.ru')
    @driver.find_element(:id, 'account_password').click
    @driver.find_element(:id, 'account_password').send_keys('1')
    @driver.find_element(:name, 'commit').click
    element = @driver.find_element(:id, 'account_email')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:id, 'account_email')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:id, 'account_email')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:id, 'account_email').click
    @driver.find_element(:id, 'account_email').send_keys('f@gmail')
    @driver.find_element(:id, 'account_password').click
    @driver.find_element(:id, 'account_password').send_keys('2')
    @driver.find_element(:name, 'commit').click
    element = @driver.find_element(:css, 'body')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'body')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'body')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:css, 'body').click
    @driver.find_element(:id, 'account_email').send_keys('f')
    @driver.find_element(:css, '.field:nth-child(4)').click
    @driver.find_element(:id, 'account_password').click
    @driver.find_element(:id, 'account_password').send_keys('21')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.actions:nth-child(6)').click
    @driver.find_element(:css, '.btn-secondary').click
    @driver.find_element(:id, 'account_username').click
    @driver.find_element(:id, 'account_username').send_keys('andrew')
    @driver.find_element(:css, '.field:nth-child(3) > .col-sm-4').click
    @driver.find_element(:id, 'account_first_name').click
    @driver.find_element(:id, 'account_first_name').send_keys('Андрей')
    @driver.find_element(:id, 'account_last_name').click
    @driver.find_element(:id, 'account_last_name').send_keys('Иванов')
    @driver.find_element(:id, 'account_email').click
    @driver.find_element(:id, 'account_email').send_keys('123456')
    @driver.find_element(:id, 'account_password').click
    element = @driver.find_element(:css, 'html')
    @driver.action.move_to_element(element).click_and_hold.perform
    element = @driver.find_element(:css, 'html')
    @driver.action.move_to_element(element).perform
    element = @driver.find_element(:css, 'html')
    @driver.action.move_to_element(element).release.perform
    @driver.find_element(:css, 'html').click
    @driver.find_element(:id, 'account_password').click
    @driver.find_element(:id, 'account_password').send_keys('123456')
    @driver.find_element(:css, '.field:nth-child(7) > .col-sm-4').click
    @driver.find_element(:id, 'account_password_confirmation').click
    @driver.find_element(:id, 'account_password_confirmation').send_keys('123456')
    @driver.find_element(:id, 'account_email').click
    @driver.find_element(:id, 'account_email').click
    @driver.find_element(:id, 'account_email').send_keys('andrew@gmail.com')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:link_text, 'Ygim').click
    @driver.find_element(:link_text, 'Зачетная работа по ЯИП. Латышев Арсений ИУ6-35Б').click
    @driver.find_element(:css, '.insta-post:nth-child(7) .text-black').click
    @driver.find_element(:link_text, 'Зачетная работа по ЯИП. Латышев Арсений ИУ6-35Б').click
    @driver.find_element(:link_text, 'testuser').click
    @driver.find_element(:link_text, 'Мой профиль').click
    @driver.find_element(:link_text, 'Редактировать профиль').click
    @driver.find_element(:css, '.btn-danger').click
    @driver.find_element(:id, 'account_email').click
    @driver.find_element(:id, 'account_email').send_keys('andrew@gmail.com')
    @driver.find_element(:id, 'account_password').click
    @driver.find_element(:id, 'account_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, 'html').click
  end
end
